spring:
  application:
    name: MS_Payment
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: payment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.br.MS_Payment.framework.dto
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.br.MS_Payment.framework.dto.ReceiveOrderEvent
server:
  port: 8081